In [81]:
import pandas as pd
import numpy as np
import torch
import sklearn
import matplotlib
import torchinfo, torchmetrics

# Check PyTorch access (should print out a tensor)
print(torch.randn(3, 3))

# Check for GPU (should return True)
print(torch.cuda.is_available())

tensor([[-1.3208, -2.2562, -0.5155],
        [ 0.6722,  2.3703, -0.7795],
        [ 0.1003, -1.1676, -1.1527]])
False


In [13]:
print(torch.__version__)

2.7.0


In [6]:
# Crea un tensore casuale
x = torch.randn(3, 3)
print(f"Random tensor:\n{x}")

# Verifica disponibilità acceleratori
print(f"CUDA available: {torch.cuda.is_available()}")
print(f"MPS available: {torch.backends.mps.is_available() if hasattr(torch.backends, 'mps') else 'MPS module not found'}")

# Prova a utilizzare MPS se disponibile
if hasattr(torch.backends, 'mps') and torch.backends.mps.is_available():
    device = torch.device("mps")
    x = x.to(device)
    print(f"Tensor moved to MPS device: {x.device}")

Random tensor:
tensor([[-1.1899,  0.1600, -0.3878],
        [-0.5169, -0.7166, -0.3784],
        [-1.3063,  0.3814,  1.7909]])
CUDA available: False
MPS available: True
Tensor moved to MPS device: mps:0


## 🚨Durante il corso sostituire CUDA CON MPS🚨

`device = torch.device("cuda" if torch.cuda.is_available() else "cpu")`

diventerà

`device = torch.device("mps" if torch.backends.mps.is_available() else "cpu")`

### Funzione per rendere universale?

In [7]:
def get_device():
    if torch.backends.mps.is_available():
        return torch.device("mps")
    elif torch.cuda.is_available():
        return torch.device("cuda")
    else:
        return torch.device("cpu")

# Poi usa
device = get_device()

In [8]:
print(device)

mps


## Introduction to Tensors
### Creating tensors

I tensori PyTotch sono creati usando `torch.Tensor()` [documentazione](https://pytorch.org/docs/stable/tensors.html)

In [9]:
# scalar (non ha dimensione)

scalar = torch.tensor(7)
scalar

tensor(7)

In [12]:
scalar.ndim

0

In [14]:
# Get tensor back as Python int
scalar.item()

7

### Vector 
Array **unidimensionale** di numeri. Rappresenta una grandezza con magnitudine e direzione.
**due caratteristiche di un vettore**
* **Magnitudine (o Modulo)**: È la lunghezza o grandezza del vettore. Rappresenta quanto è "lungo" il vettore nello spazio. Per un vettore v in uno spazio n-dimensionale, la magnitudine si calcola come la radice quadrata della somma dei quadrati delle sue componenti:
$||v|| = √(v₁² + v₂² + ... + vₙ²)$
* **Direzione**: È l'orientamento del vettore nello spazio. Indica verso dove punta il vettore ed è determinata dagli angoli che il vettore forma con gli assi di riferimento. Un vettore unitario (con magnitudine 1) nella stessa direzione del vettore originale può essere ottenuto dividendo il vettore per la sua magnitudine:
$û = v / ||v||$

Queste due caratteristiche insieme definiscono completamente un vettore: quanto è lungo (magnitudine) e verso dove punta (direzione). In PyTorch e nel machine learning, queste proprietà sono fondamentali per molte operazioni, come la normalizzazione dei vettori, il calcolo di distanze e similitudini, e l'ottimizzazione dei gradienti.

In [15]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [16]:
vector.ndim

1

In [17]:
vector.shape

torch.Size([2])

### Matrix
Array **bidimensionale** di numeri organizzati in righe e colonne. Trasforma vettori in altri vettori.
Dimensioni: Una matrice è caratterizzata dal numero di righe e colonne (m×n), che definiscono la sua forma.

In [18]:
MATRIX = torch.tensor([[7, 8], 
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [19]:
MATRIX.ndim

2

In [20]:
MATRIX[1]

tensor([ 9, 10])

In [22]:
MATRIX.shape

torch.Size([2, 2])

## TENSOR
Generalizzazione **multidimensionale** di vettori e matrici. Un array n-dimensionale di numeri. Un vettore è un tensore di rango 1, una matrice è un tensore di rango 2, mentre un tensore può avere rango 3 o superiore. 

Esempio di tensore 3D: `[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]`.

Nel deep learning, i tensori sono l'unità fondamentale di dati: immagini (tensori 4D), sequenze di testo (tensori 3D), pesi delle reti (tensori di vari ranghi).

In [23]:
TENSOR = torch.tensor([[[1,2,3],
                       [3,6,9],
                       [2,3,4]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 3, 4]]])

In [25]:
TENSOR.ndim

3

In [26]:
TENSOR.shape

torch.Size([1, 3, 3])

In [27]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 3, 4]])

In [31]:
TENSOR[0][1]

tensor([3, 6, 9])

In [32]:
TENSOR[0][1][2]

tensor(9)

| **Name** | **What is it?** | **Number of dimensions** | **Lower or upper (usually/example)** |
|----------|------------|--------------------------|-------------------------------------|
| **scalar** | a single number | 0 | Lower (a) | 
| **vector** | a number with direction (e.g. wind speed with direction) but can also have many other numbers | 1 | Lower (y) |
| **matrix** | a 2-dimensional array of numbers | 2 | Upper (Q) |
| **tensor** | an n-dimensional array of numbers | can be any number, a 0-dimension tensor is a scalar, a 1-dimension tensor is a vector | Upper (X) |

## Random Tensors

I tensori randomici sono importanti perchè il modo in cui le reti neurali imparano, è iniziare con un tensore pieno di numeri randomici e poi aggiustano questi numeri per una rappresentazione migliore dei dati.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...`

In [34]:
# Create a random tensor of shape(size) (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.1070, 0.0685, 0.2837, 0.4913],
        [0.0442, 0.1371, 0.0126, 0.7032],
        [0.7393, 0.0785, 0.3405, 0.2403]])

In [35]:
random_tensor.ndim

2

In [36]:
random_tensor.shape

torch.Size([3, 4])

In [42]:
# create a random tensor with a similar shape to an image
random_image_size_tensor = torch.rand(size=(3, 224,224)) # colour channels (R,G,B), height, width, 
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

![tensore](image/00-tensor-shape-example-of-image.png)

## Zeros and Ones

In [45]:
# Creating Tensor of all zeros (esempio di mask)
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [48]:
# Creating Tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [49]:
ones.dtype

torch.float32

## Creating a range of tensors and tensors-like

In [61]:
# torch.arange(start, end, step)
one_to_ten = torch.arange(start=0,end=11, step=1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
# Creating a tensor like
ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Il comando `torch.zeros_like(input=one_to_ten)` crea un nuovo tensore con:

* La stessa forma (dimensioni) del tensore one_to_ten
* Lo stesso tipo di dati (dtype) del tensore one_to_ten
* Lo stesso dispositivo (CPU o GPU) del tensore one_to_ten

Ma con tutti gli elementi inizializzati a zero.
Per esempio:

- Se `one_to_ten` è un vettore di lunghezza 10, ten_zeroes sarà un vettore di lunghezza 10 contenente solo zeri
- Se `one_to_ten` è una matrice 3×4, ten_zeroes sarà una matrice 3×4 contenente solo zeri

**Questo è molto utile quando hai bisogno di creare un tensore con le stesse caratteristiche di un tensore esistente, ma con valori diversi**. Altri metodi simili includono:

- `torch.ones_like()`: come zeros_like ma riempie con 1
- `torch.randn_like()`: stessa forma ma con valori casuali da una distribuzione normale
- `torch.rand_like()`: stessa forma ma con valori casuali uniformi tra 0 e 1
- `torch.empty_like()`: stessa forma ma senza inizializzare i valori (per performance)

Se invece volessi creare un tensore con la stessa forma ma con un dtype o dispositivo diverso, potresti specificarlo:

`pythonten_zeroes = torch.zeros_like(one_to_ten, dtype=torch.float32, device="mps")`

## Tensor Datatypes
- Il `dtype` è per la **precision in computing**
    - **Precision** is the amount of detail used to describe a number.
      The higher the precision value (8, 16, 32), the more detail and hence data
      used to express a number. This matters in deep learning and numerical computing because you're making so many operations, the more detail you have to calculate on, the more compute you have to use. So lower precision datatypes are generally faster to compute on but sacrifice some performance on evaluation metrics like accuracy (faster to compute but less accurate).
- `device` what device is the tensor stored on? (usually GPU or CPU)
- `require_grad` se vogliamo o meno calcolare i gradienti

In [64]:
# Float 32 tensor (è il default)
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                              dtype=None, # What datatype is the tensor (e.g. float32 or float16)
                              device=None, # defaults to None, which uses the default tensor type
                              requires_grad=False) # if True, operations performed on the tensor are recorded
float_32_tensor

tensor([3., 6., 9.])

In [63]:
float_32_tensor.dtype

torch.float32

In [65]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

## Getting Tensor Attributes
- check tensor datatype `tensor.dtype`
- check tensor shape `tensor.shape`
- check tensor device(GPU|TPU) `tensor.device`

In [66]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.7819, 0.0979, 0.0121, 0.7729],
        [0.7100, 0.4248, 0.3079, 0.2666],
        [0.6290, 0.9386, 0.5207, 0.8704]])

In [67]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.7819, 0.0979, 0.0121, 0.7729],
        [0.7100, 0.4248, 0.3079, 0.2666],
        [0.6290, 0.9386, 0.5207, 0.8704]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


## Manipulating Tensors (Tensor Operations)
Le operazioni sui tensori includono:
- Addizioni
- Sottrazioni
- Moltiplicazioni (element-wise)
- Divisioni
- Matrix Multiplication

In [68]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])

tensor + 10

tensor([11, 12, 13])

In [69]:
# multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [70]:
# subtract 10
tensor -10

tensor([-9, -8, -7])

In [72]:
# in-built function
torch.mul(tensor,10) # torch.add(tensor,10)

tensor([10, 20, 30])

## Moltiplicazione di Matrici (dot product)
La moltiplicazione di matrici è un'operazione fondamentale in algebra lineare con importanti applicazioni nel machine learning e deep learning. 

Le due regole principali sono:

**La dimensione interna deve combaciare**:

- `(3, 2) @ (3, 2)` won't work
- `(2, 3) @ (3, 2)` will work
- `(3, 2) @ (2, 3)` will work
  
**La matriche risultante avrà la forma delle dimensioni esterne**:

- `(2, 3) @ (3, 2) -> (2, 2)`
- `(3, 2) @ (2, 3) -> (3, 3)`
> Note: "@" in Python is the symbol for matrix multiplication.

![matrix mul](image/matrix_mul.png)
[sito math is fun](https://www.mathsisfun.com/algebra/matrix-multiplying.html)

Ecco in cosa consiste:
**Definizione Formale**
Per moltiplicare due matrici A (di dimensione m×n) e B (di dimensione n×p), il risultato sarà una matrice C (di dimensione m×p) dove:
$C[i,j] = \sum_{k=0}^{n-1} A[i,k] × B[k,j]$
In parole semplici, ogni elemento $C[i,j]$ della matrice risultante è il prodotto scalare della riga i-esima di A con la colonna j-esima di B.

**Caratteristiche Chiave**
- **Non è commutativa**: In generale, A×B ≠ B×A.
- **Dimensioni compatibili**: Per poter moltiplicare due matrici, il numero di colonne della prima matrice deve essere uguale al numero di righe della seconda.
- **Complessità computazionale**: O(n³) per l'algoritmo naïve, ma esistono algoritmi più efficienti come Strassen (O(n^2.8)).
- **Interpretazione geometrica**: Rappresenta una composizione di trasformazioni lineari.

**Esempio Semplice**

Per moltiplicare:

`A = [[1, 2],[3, 4]]`
`B = [[5, 6],[7, 8]]`

Il risultato sarà:

`C = [[19, 22],[43, 50]]`

Dove:
```
C[0,0] = A[0,0]×B[0,0] + A[0,1]×B[1,0] = 1×5 + 2×7 = 19
C[0,1] = A[0,0]×B[0,1] + A[0,1]×B[1,1] = 1×6 + 2×8 = 22
C[1,0] = A[1,0]×B[0,0] + A[1,1]×B[1,0] = 3×5 + 4×7 = 43
C[1,1] = A[1,0]×B[0,1] + A[1,1]×B[1,1] = 3×6 + 4×8 = 50
```

In [73]:
# Element wise multiplication

print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [74]:
# Matrix Multiplication

torch.matmul(tensor,tensor)

tensor(14)

In [75]:
tensor

tensor([1, 2, 3])

In [76]:
# matrix multiplication by hand
1*1+2*2+3*3

14

In [82]:
## Differenze di calcolo
%time
value = 0
for i in range(len(tensor)):
    value+= tensor[i] * tensor[i]
print(value)

CPU times: user 3 μs, sys: 1e+03 ns, total: 4 μs
Wall time: 6.91 μs
tensor(14)


In [83]:
%time
torch.matmul(tensor, tensor)

CPU times: user 4 μs, sys: 2 μs, total: 6 μs
Wall time: 10 μs


tensor(14)

## 🚨 Tensors shape error

💡 [sito matrix multiplication](http://matrixmultiplication.xyz/) 💡, molto simpatico mostra visivamente come viene effettuata un matrix multiplication

In [156]:
# Shape for matrix multiplication
tensor_A = torch.tensor([[1,2],
                       [3,4],
                       [5,6]])

tensor_B = torch.tensor([[7,10],
                       [8,11],
                       [9,12]])

# torch.mm(tensor_A, tensor_B) # `torch_mm` is = `torch.matmul`
# torch.matmul(tensor_A, tensor_B)

### Transpose
To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**

**transpose** inverte gli assi o le dimensioni di un dato vettore. 

In [89]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [88]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [93]:
# the matrix mult funziona quando il tensor_b ha un transpose
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape}, tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <-- inner dimension must match")
print("Ouput:\n")
output =  torch.matmul(tensor_A, tensor_B.T)

print(output)

print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <-- inner dimension must match
Ouput:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [102]:
# Create a tensor
x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [99]:
# find min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [100]:
# find max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [107]:
# find the mean
# NOTA: `torch.mean() rechiede un tensore di tipo float32
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [108]:
# find the sum

torch.sum(x), x.sum()

(tensor(450), tensor(450))

### find argmax e argmin
ci tornerà utile quando useremo il layer **softmax**

In [120]:
 x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [116]:
# trova l'indice del valore più grande
torch.argmax(x), x.argmax()

(tensor(9), tensor(9))

In [117]:
x[9]

tensor(90)

In [115]:
# trova l'indice del valore più piccolo
torch.argmin(x), x.argmin()

(tensor(0), tensor(0))

In [118]:
x[0]

tensor(0)

## Reshaping stacking, squeezing and unsqueezing tensors

* **Reshaping** - reshapes an input tensor to a defined shape (**deve essere compatili con la shape iniziale**)
* **View** - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* **Stacking** - combine multiple tensors on top of each other (**vstack**) or side by side (**hstack**)
* **Squeeze** - remove all `1` dimension from a tensor
* **UnSqueeze** - add  a `1` dimension to a target tensor
* **Permute** - Return a view of the input with dimension permuted (swapped) in a certain way

In [121]:
# Let's create a tensor
import torch
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

### Reshape
Rimodella un tensore di input in una forma definita (deve essere compatibile con la forma iniziale, cioè il numero totale di elementi deve rimanere invariato).

In [135]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [136]:
x_reshaped_2 = x.reshape(9,1)
x_reshaped_2, x_reshaped_2.shape

(tensor([[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

### View
Restituisce una vista di un tensore di input con una certa forma ma mantiene la stessa memoria del tensore originale. Le modifiche alla vista modificheranno anche il tensore originale poiché condividono gli stessi dati sottostanti.
**view** condivide la memoria con il tensore originale
Cambiare `z` cambia `x` in quando una **view** di un tensore condivide la stessa memoria con l'inpunt originale

In [126]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [131]:
# Se cambiamo il primo elemento in z, 
# avverrà lo stesso nel tensore originale
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

### Stacking
Combina più tensori uno sopra l'altro (vstack) o uno accanto all'altro (hstack). 
* `dim=0` **vstack**
* `dim=1` **hstack**

In [132]:
x_stacked = torch.stack([x,x,x,x], dim = 0) # vstack
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [133]:
x_stacked = torch.stack([x,x,x,x], dim = 1) # hstack
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

### Squeeze & Unsqueeze
`torch.squeeze()` remove all single dimensions from a target tensor

Rimuove tutte le dimensioni di grandezza 1 da un tensore. Ad esempio, trasformare un tensore di forma `[1, 3, 1, 2]` in uno di forma `[3, 2]`.

In [148]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous Shape: {x_reshaped.shape}")

# Remove extra dimensions
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New Shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous Shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New Shape: torch.Size([9])


`torch.unsqueeze()` add a single dimensions to a target tensor at specific dim (dimension)

Aggiunge una dimensione di grandezza 1 a un tensore target. Ad esempio, trasformare un vettore di forma `[3]` in una matrice di forma `[1, 3]` o `[3, 1]`, a seconda dell'indice specificato.

🚀 L'operazione `unsqueeze` è molto utile nel deep learning quando hai bisogno di adattare la forma dei tensori per operazioni specifiche, come **aggiungere una dimensione di batch** o una **dimensione di canale per le immagini**.

In [155]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous Shape: {x_reshaped.shape}")

# add extra dimensions
x_unsqueezed = x_reshaped.unsqueeze(2)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New Shape: {x_unsqueezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous Shape: torch.Size([1, 9])

New tensor: tensor([[[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]])
New Shape: torch.Size([1, 9, 1])


#### Come leggere le forme dei tensori
ad esempio `torch.Size([1, 9, 1])` è un tensore 3D con:


* 1 "blocco"
* Contenente 9 "righe"
* Ciascuna "riga" ha 1 solo valore

**Suggerimento visivo:**
Per un tensore di forma `[a, b, c, ...]`:

* Pensa a a come al numero di "scatole"
* Ogni scatola contiene b "righe"
* Ogni riga contiene c "colonne"

### Permute
`torch.permute` - rearrages the dimensions of a target tensor in a specified order

Restituisce una **vista** (condivide la stessa memoria) del tensore di input con le dimensioni permutate (scambiate) in un certo modo. Ad esempio, trasformare un tensore di forma `[64, 3, 224, 224]` (**batch, canali, altezza, larghezza**) in `[64, 224, 224, 3]` per cambiare l'ordine delle dimensioni.

In [157]:
x_original = torch.rand(size=(224,224,3)) # [height, width, colour_channels

# permute the original tensor to rearrrange the axis (or dim) order

x_permuted = x_original.permute(2,0,1) # shifts axis 0->1, 1->2, 2->0


print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}" )

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])
